bundler_args: --without guard
script:
  - "bundle exec rspec spec"
language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
